name: Check Website Status

on:
  schedule:
    - cron: '0 * * * *' # Runs at 00:00 UTC every day

jobs:
  check-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Website Status
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://checkin.osucoc.org | grep 200 || exit 1
        continue-on-error: true # Allow the workflow to continue even if the request fails

